<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Base;

use MU\CommentsModule\Listener\EntityLifecycleListener;

/**
 * Events definition base class.
 */
abstract class AbstractCommentsEvents
{
    /**
     * The mucommentsmodule.itemactionsmenu_pre_configure event is thrown before the item actions
     * menu is built in the menu builder.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\ConfigureItemActionsMenuEvent instance.
     *
     * @see MU\CommentsModule\Menu\MenuBuilder::createItemActionsMenu()
     * @var string
     */
    const MENU_ITEMACTIONS_PRE_CONFIGURE = 'mucommentsmodule.itemactionsmenu_pre_configure';
    
    /**
     * The mucommentsmodule.itemactionsmenu_post_configure event is thrown after the item actions
     * menu has been built in the menu builder.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\ConfigureItemActionsMenuEvent instance.
     *
     * @see MU\CommentsModule\Menu\MenuBuilder::createItemActionsMenu()
     * @var string
     */
    const MENU_ITEMACTIONS_POST_CONFIGURE = 'mucommentsmodule.itemactionsmenu_post_configure';
    /**
     * The mucommentsmodule.comment_post_load event is thrown when comments
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::postLoad()
     * @var string
     */
    const COMMENT_POST_LOAD = 'mucommentsmodule.comment_post_load';
    
    /**
     * The mucommentsmodule.comment_pre_persist event is thrown before a new comment
     * is created in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::prePersist()
     * @var string
     */
    const COMMENT_PRE_PERSIST = 'mucommentsmodule.comment_pre_persist';
    
    /**
     * The mucommentsmodule.comment_post_persist event is thrown after a new comment
     * has been created in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::postPersist()
     * @var string
     */
    const COMMENT_POST_PERSIST = 'mucommentsmodule.comment_post_persist';
    
    /**
     * The mucommentsmodule.comment_pre_remove event is thrown before an existing comment
     * is removed from the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::preRemove()
     * @var string
     */
    const COMMENT_PRE_REMOVE = 'mucommentsmodule.comment_pre_remove';
    
    /**
     * The mucommentsmodule.comment_post_remove event is thrown after an existing comment
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::postRemove()
     * @var string
     */
    const COMMENT_POST_REMOVE = 'mucommentsmodule.comment_post_remove';
    
    /**
     * The mucommentsmodule.comment_pre_update event is thrown before an existing comment
     * is updated in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::preUpdate()
     * @var string
     */
    const COMMENT_PRE_UPDATE = 'mucommentsmodule.comment_pre_update';
    
    /**
     * The mucommentsmodule.comment_post_update event is thrown after an existing new comment
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see EntityLifecycleListener::postUpdate()
     * @var string
     */
    const COMMENT_POST_UPDATE = 'mucommentsmodule.comment_post_update';
    
}
