<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractCommentsEvents
{
    /**
     * The mucommentsmodule.comment_post_load event is thrown when comments
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const COMMENT_POST_LOAD = 'mucommentsmodule.comment_post_load';
    
    /**
     * The mucommentsmodule.comment_pre_persist event is thrown before a new comment
     * is created in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const COMMENT_PRE_PERSIST = 'mucommentsmodule.comment_pre_persist';
    
    /**
     * The mucommentsmodule.comment_post_persist event is thrown after a new comment
     * has been created in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const COMMENT_POST_PERSIST = 'mucommentsmodule.comment_post_persist';
    
    /**
     * The mucommentsmodule.comment_pre_remove event is thrown before an existing comment
     * is removed from the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const COMMENT_PRE_REMOVE = 'mucommentsmodule.comment_pre_remove';
    
    /**
     * The mucommentsmodule.comment_post_remove event is thrown after an existing comment
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const COMMENT_POST_REMOVE = 'mucommentsmodule.comment_post_remove';
    
    /**
     * The mucommentsmodule.comment_pre_update event is thrown before an existing comment
     * is updated in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const COMMENT_PRE_UPDATE = 'mucommentsmodule.comment_pre_update';
    
    /**
     * The mucommentsmodule.comment_post_update event is thrown after an existing new comment
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\CommentsModule\Event\FilterCommentEvent instance.
     *
     * @see MU\CommentsModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const COMMENT_POST_UPDATE = 'mucommentsmodule.comment_post_update';
    
}
