<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\Block;

use MU\CommentsModule\Block\Base\AbstractModerationBlock;

/**
 * Moderation block implementation class.
 */
class ModerationBlock extends AbstractModerationBlock
{
    // feel free to extend the moderation block here
}
