<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Form\Type;

use MU\CommentsModule\Form\Type\Base\AbstractCommentType;

/**
 * Comment editing form type implementation class.
 */
class CommentType extends AbstractCommentType
{
    // feel free to extend the comment editing form type class here
}
