<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Entity\Factory\Base;

use MU\CommentsModule\Entity\CommentEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given comment instance.
     *
     * @param CommentEntity $entity The newly created entity instance
     *
     * @return CommentEntity The updated entity instance
     */
    public function initComment(CommentEntity $entity)
    {
        return $entity;
    }

}
