<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\Entity;

use MU\CommentsModule\Entity\Base\AbstractHookAssignmentEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity implementation class for hooked object assignments.
 *
 * @ORM\Entity()
 * @ORM\Table(name="mu_comments_hookassignment")
 */
class HookAssignmentEntity extends AbstractHookAssignmentEntity
{
    // feel free to add your own methods here
}
