<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\DependencyInjection;

use MU\CommentsModule\DependencyInjection\Base\AbstractMUCommentsExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUCommentsExtension extends AbstractMUCommentsExtension
{
    // custom enhancements can go here
}
