<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Twig;

use MU\CommentsModule\Twig\Base\AbstractTwigExtension;
use Symfony\Component\HttpKernel\Controller\ControllerReference;

use Zikula\Common\Translator\TranslatorInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use MU\CommentsModule\Helper\ListEntriesHelper;
use MU\CommentsModule\Helper\EntityDisplayHelper;
use MU\CommentsModule\Helper\WorkflowHelper;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpKernel\Fragment\FragmentHandler;

/**
 * Twig extension implementation class.
 */
class TwigExtension extends AbstractTwigExtension
{
	/**
	 * @var Request
	 */
	protected $request;
	
	/**
	 * @var FragmentHandler
	 */
	protected $fragmentHandler;
	
	/**
	 * TwigExtension constructor.
	 *
	 * @param TranslatorInterface $translator     Translator service instance
	 * @param VariableApiInterface   $variableApi    VariableApi service instance
	 * @param EntityDisplayHelper $entityDisplayHelper EntityDisplayHelper service instance
	 * @param WorkflowHelper      $workflowHelper WorkflowHelper service instance
	 * @param ListEntriesHelper   $listHelper     ListEntriesHelper service instance
	 * @param RequestStack           $requestStack     RequestStack service instance
	 * @param FragmentHandler    $fragmentHandler FragmentHandler service instance
	 */
	public function __construct(
			TranslatorInterface $translator,
			VariableApiInterface $variableApi,
			EntityDisplayHelper $entityDisplayHelper,
			WorkflowHelper $workflowHelper,
			ListEntriesHelper $listHelper,
			RequestStack $requestStack,
			FragmentHandler $fragmentHandler)
	{
		$this->setTranslator($translator);
		$this->variableApi = $variableApi;
		$this->entityDisplayHelper = $entityDisplayHelper;
		$this->workflowHelper = $workflowHelper;
		$this->listHelper = $listHelper;
		$this->request = $requestStack->getCurrentRequest();
		$this->fragmentHandler = $fragmentHandler;
	}
	
     /** Returns a list of custom Twig functions.
     *
     * @return array
     */
    public function getFunctions()
    {
    	$functions = parent::getFunctions();
    	$functions[] = new \Twig_SimpleFunction('mucommentsmodule_showEditForm', [$this, 'showEditForm'], ['is_safe' => ['html'], 'owner']);
 	
    	return $functions;
    }
    
    public function showEditForm($owner, $area, $object)
    {
    	$this->request->attributes->set('_zkModule', 'MUCommentsModule');
    
    	$ref = new ControllerReference('MUCommentsModule:Comment:edit', array('owner' => $owner, 'area' => $area, 'object' => $object));
    
    	return $this->fragmentHandler->render($ref, 'inline', []);
    }
}
