<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Twig;

use MU\CommentsModule\Twig\Base\AbstractTwigExtension;
use Symfony\Component\HttpKernel\Controller\ControllerReference;
use ServiceUtil;

/**
 * Twig extension implementation class.
 */
class TwigExtension extends AbstractTwigExtension
{
     /** Returns a list of custom Twig functions.
     *
     * @return array
     */
    public function getFunctions()
    {
    	$functions = parent::getFunctions();
    	$functions[] = new \Twig_SimpleFunction('mucommentsmodule_showEditForm', [$this, 'showEditForm'], ['is_safe' => ['html'], 'owner']);
 	
    	return $functions;
    }
    
    public function showEditForm()
    {
    	$request = \ServiceUtil::get('request_stack')->getMasterRequest();
    	$request->attributes->set('_zkModule', 'MUCommentsModule');
    
    	$fragmentHandler = \ServiceUtil::get('fragment.handler');
    
    	$ref = new ControllerReference('MUCommentsModule:Comment:edit');
    
    	return $fragmentHandler->render($ref, 'inline', []);
    }
}
