<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\ContentType;

use MU\CommentsModule\ContentType\Base\AbstractItem;

/**
 * Generic single item display content plugin implementation class.
 */
class Item extends AbstractItem
{
    // feel free to extend the content type here
}
