<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.0.1 (https://modulestudio.de).
 */

namespace MU\CommentsModule\HookSubscriber;

use MU\CommentsModule\HookSubscriber\Base\AbstractCommentFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class CommentFormAwareHookSubscriber extends AbstractCommentFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
