<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Form\Type\QuickNavigation;

use MU\CommentsModule\Form\Type\QuickNavigation\Base\AbstractCommentQuickNavType;

/**
 * Comment quick navigation form type implementation class.
 */
class CommentQuickNavType extends AbstractCommentQuickNavType
{
    // feel free to extend the base form type class here
}
