<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule\Entity\Repository;

use MU\CommentsModule\Entity\Repository\Base\AbstractCommentRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for comment entities.
 */
class CommentRepository extends AbstractCommentRepository
{    
	/**
	 * @var string The default sorting field/expression
	 */
	protected $defaultSortingField = 'createdDate';
}
