services:
    mu_comments_module.app_settings:
        class: MU\CommentsModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
