services:
    # Event subscribers and listeners
    mu_comments_module.entity_lifecycle_listener:
        class: MU\CommentsModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - { name: doctrine.event_subscriber }
    
    mu_comments_module.kernel_listener:
        class: MU\CommentsModule\Listener\KernelListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.installer_listener:
        class: MU\CommentsModule\Listener\InstallerListener
        arguments:
            - "@mu_comments_module.entity_factory"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.moduledispatch_listener:
        class: MU\CommentsModule\Listener\ModuleDispatchListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.mailer_listener:
        class: MU\CommentsModule\Listener\MailerListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.theme_listener:
        class: MU\CommentsModule\Listener\ThemeListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.userlogin_listener:
        class: MU\CommentsModule\Listener\UserLoginListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.userlogout_listener:
        class: MU\CommentsModule\Listener\UserLogoutListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.user_listener:
        class: MU\CommentsModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@mu_comments_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.userregistration_listener:
        class: MU\CommentsModule\Listener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.users_listener:
        class: MU\CommentsModule\Listener\UsersListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.group_listener:
        class: MU\CommentsModule\Listener\GroupListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.thirdparty_listener:
        class: MU\CommentsModule\Listener\ThirdPartyListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_comments_module.workflow_events_listener:
        class: MU\CommentsModule\Listener\WorkflowEventsListener
        arguments:
            - "@zikula_permissions_module.api.permission"
            - "@mu_comments_module.notification_helper"
        tags:
            - { name: kernel.event_subscriber }
    
