services:
    # Form types
    
    mu_comments_module.form.type.commentquicknav:
        class: MU\CommentsModule\Form\Type\QuickNavigation\CommentQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_comments_module.entity_display_helper"
            - "@mu_comments_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_comments_module.form.handler.common:
        abstract: true
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@zikula_groups_module.group_application_repository"
            - "@mu_comments_module.entity_factory"
            - "@mu_comments_module.controller_helper"
            - "@mu_comments_module.model_helper"
            - "@mu_comments_module.workflow_helper"
            - "@mu_comments_module.hook_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
    
    
    mu_comments_module.form.handler.comment:
        class: MU\CommentsModule\Form\Handler\Comment\EditHandler
        parent: mu_comments_module.form.handler.common
    
    mu_comments_module.form.type.comment:
        class: MU\CommentsModule\Form\Type\CommentType
        arguments:
            - "@translator.default"
            - "@mu_comments_module.entity_factory"
            - "@mu_comments_module.collection_filter_helper"
            - "@mu_comments_module.entity_display_helper"
            - "@mu_comments_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_comments_module.form.type.block.itemlist:
        class: MU\CommentsModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_comments_module.form.type.block.item:
        class: MU\CommentsModule\Block\Form\Type\ItemBlockType
        arguments:
            - "@translator.default"
            - "@mu_comments_module.entity_factory"
            - "@mu_comments_module.entity_display_helper"
        tags:
            - { name: form.type }
    
    mu_comments_module.form.type.commentfinder:
        class: MU\CommentsModule\Form\Type\Finder\CommentFinderType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_comments_module.form.type.config:
        class: MU\CommentsModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@mu_comments_module.listentries_helper"
        tags:
            - { name: form.type }
