services:
    # Twig extension
    mu_comments_module.twig_extension:
        class: MU\CommentsModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@mu_comments_module.entity_display_helper"
            - "@mu_comments_module.workflow_helper"
            - "@mu_comments_module.listentries_helper"
            - "@request_stack"
            - "@fragment.handler"
        public: false
        tags: ['twig.extension']