services:
    # Custom validators
    mu_comments_module.validator.list_entry.validator:
        class: MU\CommentsModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_comments_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_comments_module.validator.list_entry.validator }
