<?php
/**
 * Comments.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\CommentsModule;

use MU\CommentsModule\Base\AbstractMUCommentsModule;

/**
 * Module implementation class.
 */
class MUCommentsModule extends AbstractMUCommentsModule
{
    // custom enhancements can go here
}
